Policies presubmit: fix policy deletion
When trying to submit crrev.com/c/3996874, the policies presubmit is
hitting this error:

  Error: Each policy must be a dictionary.

This is because a removed policy is `None`, i.e. not a dictionary. Fix
the issue by filtering removed policies out of `modified_policies`.

Change-Id: Ifbbf151b47f1e1db311b4322e130ffe1cb68581f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4051466
Commit-Queue: Yann Dago <ydago@chromium.org>
Reviewed-by: Yann Dago <ydago@chromium.org>
Auto-Submit: Nicolas Ouellet-Payeur <nicolaso@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1075354}
NOKEYCHECK=True
GitOrigin-RevId: 9c6fcd87a98ce8a21ea96be655e95b8396a9f7a9