Reland "WebUI: Remove addSingletonGetter() from non-ChromeOS UIs"
This reverts commit e785f23106681e688eb2c201922af25acd884ff2.

Reason for revert: fixing typo

Original change's description:
> Revert "WebUI: Remove addSingletonGetter() from non-ChromeOS UIs"
>
> This reverts commit 58e8de80d15f38be79d977791c5d7e236a97b471.
>
> Reason for revert: [sheriff] suspecting this as a tree closure.
>
> [391/43840] ACTION //chrome/browser/resources/internals/lens:closure_compile(//build/toolchain/android:android_clang_arm64)
> FAILED: gen/chrome/browser/resources/internals/lens/closure_compile.js
> python3 ../../third_party/closure_compiler/js_binary.py --compiler ../../third_party/closure_compile...(too long)
> ../../third_party/closure_compiler/compiler/compiler.jar --jscomp_error=accessControls --jscomp_erro...(too long)
> ../../chrome/browser/resources/internals/lens/lens_internals_browser_proxy.js:7:12: ERROR - [JSC_UNRECOGNIZED_TYPE_ERROR] Bad type annotation. Unknown type LenseInternalsBrowserProxy
> 7| /** @type {?LenseInternalsBrowserProxy} */
> ^
>
> 1 error(s), 0 warning(s), 93.1% typed
>
> Original change's description:
> > WebUI: Remove addSingletonGetter() from non-ChromeOS UIs
> >
> > This method is incompatible with TypeScript compiler and no longer
> > supported on non-ChromeOS.
> >
> > Bug: 1380849
> > Change-Id: Ia1a5d86d550addd38062ce581924cf42bf4aa0ad
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3998695
> > Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
> > Reviewed-by: John Lee <johntlee@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#1067243}
>
> Bug: 1380849
> Change-Id: I6faba7f2421256aa745f41f5787a7d7983519b51
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4004125
> Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Auto-Submit: Devlin Cronin <rdevlin.cronin@chromium.org>
> Reviewed-by: Devlin Cronin <rdevlin.cronin@chromium.org>
> Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
> Owners-Override: Devlin Cronin <rdevlin.cronin@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1067267}

Bug: 1380849
Change-Id: Ia58ece9daba41c5c5eff69433a76cd31c2907cc7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4005058
Commit-Queue: John Lee <johntlee@chromium.org>
Auto-Submit: Rebekah Potter <rbpotter@chromium.org>
Commit-Queue: Rebekah Potter <rbpotter@chromium.org>
Reviewed-by: Devlin Cronin <rdevlin.cronin@chromium.org>
Reviewed-by: John Lee <johntlee@chromium.org>
Commit-Queue: Devlin Cronin <rdevlin.cronin@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1067361}
NOKEYCHECK=True
GitOrigin-RevId: 2a89babeb665be08ddada7cfba0ef29f218369e4