Avoid HTTP_STATUS macro clash on MacOSX13.0.sdk.
This was detected by a WebRTC bot:

In file included from ../../net/test/embedded_test_server/http_response.h:19:
../../net/http/http_status_code.h:15:9: error: 'HTTP_STATUS' macro redefined [-Werror,-Wmacro-redefined]
        ^
sdk/xcode_links/MacOSX13.0.sdk/usr/include/cups/http.h:225:13: note: previous definition is here
            ^
1 error generated.

Bug: webrtc:14342
Change-Id: I9df431360a8c9259d1d3ae2fe559a14b90c3a373
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3830307
Reviewed-by: Ryan Hamilton <rch@chromium.org>
Reviewed-by: Fabio Tirelo <ftirelo@chromium.org>
Commit-Queue: Mirko Bonadei <mbonadei@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1034996}
NOKEYCHECK=True
GitOrigin-RevId: 2a81ba40e8d47380f4e9cf32897f9e6bbf4d5ed6