Improve failure logging in PolicyPrefsTest.PolicyToPrefsMapping.
This test loops over everything in policy_test_cases.json to assert
various things. On failure, it can be tricky to know where the problem
is. Here, we sprinkle in a few calls to SCOPED_TRACE() so that failures
look like this:

.../policy_pref_mapping_test.cc(108): error: Value of: pref->IsDefaultValue()
  Actual: false
Expected: true
Google Test trace:
.../policy_pref_mapping_test.cc(613): Pref: webrtc.event_logs_collection
.../policy_pref_mapping_test.cc(600): Mapping test index 0
.../policy_pref_mapping_test.cc(573): Policy name: WebRtcEventLogCollectionAllowed

So now we know to look in the WebRtcEventLogCollectionAllowed block at
the first item in policy_pref_mapping_tests where
webrtc.event_logs_collection was expected to be set to its default
value.

Bug: none
Change-Id: I87892dfff432ce693614ea48e635d7691d355a15
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3132602
Auto-Submit: Greg Thompson <grt@chromium.org>
Commit-Queue: Julian Pastarmov <pastarmovj@chromium.org>
Reviewed-by: Julian Pastarmov <pastarmovj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#916766}
NOKEYCHECK=True
GitOrigin-RevId: e4ee517522ca54587c889f8bb8162ccfe4e717d9