Add AllowNativeNotifications policy
The preference native_notifications.disabled has been renamed to
native_notifications.allowed (and is not logically negated) since
policies cannot have "Disabled" appearing in their name.  This
fixes a presubmit check of the form:

Error: Boolean policy NativeNotificationsDisabled uses negative
polarity, please make new boolean policies follow the XYZEnabled
pattern. See also http://crbug.com/85687

The new policy maps to the native_notifications.allowed preference.

R=thestig

Bug: b/72535204
Change-Id: Ib57a6f5c95e89213f507f496e3ca1904694ad965
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2055391
Auto-Submit: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Pavol Marko <pmarko@chromium.org>
Reviewed-by: Peter Beverloo <peter@chromium.org>
Reviewed-by: Pavol Marko <pmarko@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#741423}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f2cd0b128d67c11c3aca2d2a6e6f3a2c3cbc7b2a