Revert "[policy presubmit] Merge two presubmits"
This reverts commit 357828e0f252efa2e36fa5ebe26a293ceb8e7c11.

Reason for revert: This change broke some presubmits. Typical errors
are:

** Presubmit ERRORS: 1 **
Syntax error(s) in file:
  components\policy\resources\templates

***************
Error: In policy NativePrinters: Validation schema is invalid
  ID 'PpdResource' is not unique.
  ID 'PrinterType' is not unique.
Error: In policy Printers: Validation schema is invalid
  ID 'PpdResourceInclusive' is not unique.
  ID 'PrinterTypeInclusive' is not unique.
***************

This can most easily be reproduced with this command:

    git cl presubmit --force --files "components/policy/*"

This was found by the presubmit --all builder and first showed up
in this build:

https://ci.chromium.org/ui/p/chromium/builders/ci/linux-presubmit/2945/overview

Original change's description:
> [policy presubmit] Merge two presubmits
>
> * Move components/policy/resources/PRESUBMIT.py on level up - so it's
> triggered also by the syntax checker changes
> * Run the syntax checker against the whole list of policy in case the
> checker has changed
> * Small refactoring of the constant paths
> * Change contacts for the presubmit
>
> BUG=b:266377723
>
> Change-Id: Ifdd05565c844661efe5441e38278042a02794084
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4181112
> Commit-Queue: Roman Sorokin <rsorokin@google.com>
> Reviewed-by: Yann Dago <ydago@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1099121}

Bug: b:266377723
Change-Id: If17b64334d1c4c8559f428d6102963dc8b9ebfd7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4218657
Commit-Queue: Roman Sorokin <rsorokin@google.com>
Reviewed-by: Roman Sorokin <rsorokin@google.com>
Cr-Commit-Position: refs/heads/main@{#1100882}
NOKEYCHECK=True
GitOrigin-RevId: 346ef440544617f01c8a05bb6ba5d94f08d33862