Revert "Restrict CertificateManagementAllowed policy"
This reverts commit 063cdeef85278e72ef66db1dd3f1b5bdf8f3c543.

Reason for revert:

Likely causes of deterministic failures on linux-chromeos-dbg bot since it was submitted.
https://ci.chromium.org/p/chromium/builders/ci/linux-chromeos-dbg/13333

Failing viz_browser_tests item CrSettingsPeoplePageKerberosAccountsTest.All

Failure looks like:
[ RUN      ] CrSettingsPeoplePageKerberosAccountsTest.All
[1:1:0711/125719.782650:INFO:hugepage_text.cc(96)] Mlocking text pages failed: Cannot allocate memory (12)
[12029:12029:0711/125720.228069:INFO:content_main_runner_impl.cc(981)] Chrome is running in full browser mode.
[12029:12029:0711/125721.406902:INFO:remote_commands_service.cc(38)] Fetching remote commands.
[12029:12029:0711/125721.407222:WARNING:remote_commands_service.cc(40)] Client is not registered.
[12029:12029:0711/125721.408386:INFO:remote_commands_invalidator.cc(34)] Initialize RemoteCommandsInvalidator.
[12029:12029:0711/125721.408549:INFO:remote_commands_invalidator.cc(59)] Starting RemoteCommandsInvalidator.
[12029:12029:0711/125721.408652:INFO:remote_commands_invalidator.cc(130)] RemoteCommandsInvalidator ReloadPolicyData.
[12029:12029:0711/125721.408726:INFO:remote_commands_invalidator.cc(172)] Unregister RemoteCommandsInvalidator.
[12029:12029:0711/125721.821717:WARNING:wallpaper_controller_client.cc(328)] Cannot get wallpaper files id in RemovePolicyWallpaper. This should never happen under normal circumstances.
[12029:12029:0711/125722.620525:ERROR:gcm_driver_desktop.cc(1094)] Unable to get the InstanceID data: cannot start the GCM Client
[12140:12201:0711/125722.698217:WARNING:simple_synchronous_entry.cc(1389)] Could not open platform files for entry.
[1:1:0711/125722.911602:ERROR:utility_service_factory.cc(200)] Ignoring request to start unknown service: cups_proxy
[12029:12029:0711/125723.200521:ERROR:account_manager_migrator.cc(249)] Could not find a refresh token for the Device Account.
[12029:12029:0711/125726.095357:WARNING:CONSOLE(0)] "HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.", source:  (0)
[12029:12029:0711/125729.770017:INFO:CONSOLE(1195)] "Running TestCase CrSettingsPeoplePageKerberosAccountsTest.All", source: file:///b/s/w/ir/chrome/test/data/webui/test_api.js (1195)
[12029:12029:0711/125731.368557:WARNING:CONSOLE(11)] "Could not find style data in module named action-link", source: chrome://resources/polymer/v1_0/polymer/polymer-extracted.js (11)
[12029:12029:0711/125735.550983:ERROR:CONSOLE(155)] "Uncaught (in promise) TypeError: this.$$(...).show is not a function", source: chrome://settings/people_page/kerberos_accounts.js (155)
[12029:12029:0711/125735.763001:ERROR:CONSOLE(49)] "Mocha test failed: KerberosAccountsTests RemoveAccountShowsToast
AssertionError: expected undefined to be false
    at Function.assert.isFalse (file:///b/s/w/ir/third_party/chaijs/chai.js:2459:31)
    at assertFalse (file:///b/s/w/ir/chrome/test/data/webui/test_api.js:788:15)
    at Context.<anonymous> (file:///b/s/w/ir/chrome/test/data/webui/settings/people_page_kerberos_accounts_test.js:257:7)
", source: file:///b/s/w/ir/chrome/test/data/webui/mocha_adapter.js (49)
[12029:12029:0711/125749.460448:ERROR:web_ui_test_handler.cc(72)] Test Errors: 1/37 tests had failed assertions.
[12029:12029:0711/125749.460716:ERROR:web_ui_browser_test.cc(542)] CONDITION FAILURE: encountered javascript console error(s):
[12029:12029:0711/125749.460773:ERROR:web_ui_browser_test.cc(544)] JS ERROR: '[12029:12029:0711/125735.550983:ERROR:CONSOLE(155)] "Uncaught (in promise) TypeError: this.$$(...).show is not a function", source: chrome://settings/people_page/kerberos_accounts.js (155)
'...

For more details, see http://crbug.com/983568


Original change's description:
> Restrict CertificateManagementAllowed policy
> 
> This cl restricts CertificateManagementAllowed policy to client
> certificates only and renames it to ClientCertificateManagementAllowed.
> 
> This is the first step towards creating a separate
> policy that manages user permissions over CA certificates in the Chrome
> certificate manager UI.
> 
> Bug:958455
> Test:- manually tested that importing and deleting CA certificates
> works regardless of policy settings
>       - manually tested that importing and deleting client certificates
> works according to policy
> 
> Change-Id: Id0aaf44f3bc4e3a22e99904234be3fd5343dce78
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1690862
> Commit-Queue: Andreea-Elena Costinas <acostinas@google.com>
> Reviewed-by: Ryan Sleevi <rsleevi@chromium.org>
> Reviewed-by: Steven Bennetts <stevenjb@chromium.org>
> Reviewed-by: Pavol Marko <pmarko@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#676384}

TBR=stevenjb@chromium.org,rsleevi@chromium.org,pmarko@chromium.org,acostinas@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 958455
Change-Id: Iffc9c2a3b983d2032a45ccfa80efc6be88712cd4
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1699200
Reviewed-by: Mark Pearson <mpearson@chromium.org>
Commit-Queue: Mark Pearson <mpearson@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#677070}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f6cb04c137963c9863de163293d2cc460928c4a2